name: login_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  http: ^1.1.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.0.0
  google_maps_flutter: ^2.5.3
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/google_logo.png